app.py
from flask import Flask  


def create_app():
    app = Flask(__name__)

    from views import main
    app.register_blueprint(main)
    

    return app

views.py
from flask import Flask, render_template, blueprints, request
from flask.helpers import url_for
from werkzeug.utils import redirect

main = blueprints.Blueprint('main', __name__)


# aqui se puede poner otro atributo (methods=['GET´, 'POST'])#
@main.route('/')
def index():
    return render_template('index.html')


@main.route('/hacerLogin',  methods=['POST'])
def hacerLogin():
    print(request.method)
    if request.method == 'POST':
        return redirect(url_for('main.feed'))
    return render_template('feed.html')


@main.route('/feed/')
def feed():
    return render_template('feed.html')


@main.route('/register/')
def register():
    return render_template('registro.html')


@main.route('/user_space/')
def mi_espacio():
    return render_template('mi_espacio.html')


@main.route('/search_results/')
def resultados():
    return render_template('search_result.html')


@main.route('/explore/')
def explorar():
    return render_template('explorar.html')


@main.route('/admin_profile/')
def admin_user():
    return render_template('admin_profile.html')


@main.route('/admin_dashboard/')
def dashboard():
    return render_template('dashboard.html')


@main.route('/messages/')
def mensajes():
    return render_template('mensajes.html')


@main.route('/alerts/')
def notificaciones():
    return render_template('notificaciones.html')


@main.route('/new_post/')
def post():
    return render_template('nuevo_post.html')


@main.route('/user_profile/')
def perfil_user():
    return render_template('user_profile.html')


@main.route('/new_password/')
def newpass():
    return render_template('cambPassword.html')


@main.route('/suggestions/')
def relacionate():
    return render_template('relacionate.html')

templates/borrador.html
<div id ="barra_estado"> 
        
    <div id="ctn-bars-search"> <!--search-input-->
        <a href="" target="_blank" hidden></a>
            <input type="text" id="inputSearch" placeholder="¿buscas a alguien? Escribe su nombre aquí" > <!--id="inputSearch"-->
            
            <div id="ctn-icon-search"> <!--<a href="{{url_for('main.resultados')}}">--><i class="fas fa-search" id="icon-search"></i></a> <!--id="icon-search"-->
            </div>
            <ul id ="box-search"> 
                <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> luisa</a></a></li>
                <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> leo</a></a></li>
                <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> shakira</a></a></li>
                <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> marco</a></a></li>
                <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> daniela</a></a></li>
                <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> jbalvin</a></a></li>
                
            </ul>
            <!--<div class="icon"><i class="fas fa-search"></i></div>-->
        </div>

   
    <!--<h2 class="icon_text">Cairina Moschata</h2> cambiar imagen a una con icono y letras-->
    <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/icon_cairina.jpg') }}" class="btn_icon" alt="icono de cairina"></a>
    <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/texto_logo_2.png') }}" class="txt_icon" alt="icono de cairina"></a>


    <a href="{{url_for('main.notificaciones')}}" id="btn_notification"><i class="fas fa-bell"></i></a>
    <a href="{{url_for('main.index')}}" id="btn_logout"><i class="fas fa-sign-out-alt"></i></a>
    <a href="{{url_for('main.mensajes')}}" id="btn_message"> <i class="fas fa-envelope"></i></a>
    <a href="{{url_for('main.perfil_user')}}" id="btn_user"><i class=" fas fa-user-circle"></i></i></a>
     <!-- En el div barra_estado se usan anchors en forma de botones para utilizar iconos de fontawesome
    es necesario tener las carpetas "svgs y webfonts" dentro del proyecto para que funcionen y utilizar un link como 
    se muestra en la linea 10 .....En la clase wrapper se encuenta todo lo relacionado a la barra de busqueda-->
  
</div>



<script src="../static/js/buscador.js"> </script>

templates/explorar.html
<!DOCTYPE html>
<html lang="sp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cairina Moschata</title>
    <link rel="shortcut icon"  href="../static/img/favicon.png">
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/explorar.css" />
    <link rel="stylesheet" href="../static/fontawasome/css/all.min.css">
    
</head>
<body>
    <div id ="barra_estado"> 
        
        <div id="ctn-bars-search"> <!--search-input-->
            <a href="" target="_blank" hidden></a>
                <input type="text" id="inputSearch" placeholder="¿buscas a alguien? Escribe su nombre aquí" > <!--id="inputSearch"-->
                
                <div id="ctn-icon-search"> <!--<a href="{{url_for('main.resultados')}}">--><i class="fas fa-search" id="icon-search"></i></a> <!--id="icon-search"-->
                </div>
                <ul id ="box-search"> 
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> luisa</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> leo</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> shakira</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> marco</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> daniela</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> jbalvin</a></a></li>
                    
                </ul>
                <!--<div class="icon"><i class="fas fa-search"></i></div>-->
            </div>
    
       
        <!--<h2 class="icon_text">Cairina Moschata</h2> cambiar imagen a una con icono y letras-->
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/icon_cairina.jpg') }}" class="btn_icon" alt="icono de cairina"></a>
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/texto_logo_2.png') }}" class="txt_icon" alt="icono de cairina"></a>
    
    
        <a href="{{url_for('main.notificaciones')}}" id="btn_notification"><i class="fas fa-bell"></i></a>
        <a href="{{url_for('main.index')}}" id="btn_logout"><i class="fas fa-sign-out-alt"></i></a>
        <a href="{{url_for('main.mensajes')}}" id="btn_message"> <i class="fas fa-envelope"></i></a>
        <a href="{{url_for('main.perfil_user')}}" id="btn_user"><i class=" fas fa-user-circle"></i></i></a>
         <!-- En el div barra_estado se usan anchors en forma de botones para utilizar iconos de fontawesome
        es necesario tener las carpetas "svgs y webfonts" dentro del proyecto para que funcionen y utilizar un link como 
        se muestra en la linea 10 .....En la clase wrapper se encuenta todo lo relacionado a la barra de busqueda-->
      
    </div>

    <div class="nav_menu">
        <a href="{{url_for('main.feed')}}">Inicio</a> | 

        <a href="{{url_for('main.post')}}">Nuevo Post</a> |   

        <a href="{{url_for('main.mi_espacio')}}">Tu espacio</a> | 

        <a href="{{url_for('main.relacionate')}}">Relacionate</a>

    </div>
    <h3 class="amigos">Los mas populares están aquí</h3>

    <div class="resultado_busqueda"> <!--""-->
        <img src="../static/img/shakira.jpg" alt="foto de varias personas tomandose una selfie">
        <img src="../static/img/leomessi.jpg" alt="foto de hombre jugando futbol">
        <img src="../static/img/jbalvin.jpg" alt="foto de mujer en la playa">
    </div>
    <div class="footer">
        <div class="footer-links">

          <a href="#">Terms of Use</a> | 

          <a href="#">Privacy Policy</a> | 

          <a href="#">Developers</a> | 

          <a href="#">Contact</a> | 

          <a href="#">About</a>
          <h3>Copyright © Company - All rights reserved</h3>
        </div>   
        
               
    </div>
    <script src="../static/js/buscador.js"> </script>
</body>



</html>

templates/feed.html
<!DOCTYPE html>
<html lang="sp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cairina Moschata</title>
    <link rel="shortcut icon"  href="../static/img/favicon.png">
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
    <link rel="stylesheet" href="../static/fontawasome/css/all.min.css">
</head>
<body>
    <div id ="barra_estado"> 
        
        <div id="ctn-bars-search"> <!--search-input-->
            <a href="" target="_blank" hidden></a>
                <input type="text" id="inputSearch" placeholder="¿buscas a alguien? Escribe su nombre aquí" > <!--id="inputSearch"-->
                
                <div id="ctn-icon-search"> <!--<a href="{{url_for('main.resultados')}}">--><i class="fas fa-search" id="icon-search"></i></a> <!--id="icon-search"-->
                </div>
                <ul id ="box-search"> 
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> luisa</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> leo</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> shakira</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> marco</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> daniela</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> jbalvin</a></a></li>
                    
                </ul>
                <!--<div class="icon"><i class="fas fa-search"></i></div>-->
            </div>

       
        <!--<h2 class="icon_text">Cairina Moschata</h2> cambiar imagen a una con icono y letras-->
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/icon_cairina.jpg') }}" class="btn_icon" alt="icono de cairina"></a>
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/texto_logo_2.png') }}" class="txt_icon" alt="icono de cairina"></a>


        <a href="{{url_for('main.notificaciones')}}" id="btn_notification"><i class="fas fa-bell"></i></a>
        <a href="{{url_for('main.index')}}" id="btn_logout"><i class="fas fa-sign-out-alt"></i></a>
        <a href="{{url_for('main.mensajes')}}" id="btn_message"> <i class="fas fa-envelope"></i></a>
        <a href="{{url_for('main.perfil_user')}}" id="btn_user"><i class=" fas fa-user-circle"></i></i></a>
         <!-- En el div barra_estado se usan anchors en forma de botones para utilizar iconos de fontawesome
        es necesario tener las carpetas "svgs y webfonts" dentro del proyecto para que funcionen y utilizar un link como 
        se muestra en la linea 10 .....En la clase wrapper se encuenta todo lo relacionado a la barra de busqueda-->
      
    </div>
    

    
    <div id ="titulo">
        <h1 id="feed_title">Usuario, ¿A dónde vamos? </h1>
    </div>
    
    
    
    <div class="contenido">
         <!-- se utilizan 4 divs dentro de contenido, que a su vez contienen las imagenes para poder darles estilos de manera 
        eficiente.... se utilizan anchors como botones para linkear otras vistas -->
        
        <div class="square_post">
            <img class="img_post" src="../static/img/nuevo_post.jpg" alt="imagen de una persona fotofrageando a su perro">
            <a href="{{url_for('main.post')}}" class="btn_post"><h4>Nuevo Post</h4></a>
        </div>
        <div class="square_explore">
            <img class="img_explore" src="../static/img/explorar.jpg" alt="foto de personas viendo el celular">
            <a href="{{url_for('main.explorar')}}" class="btn_explore" ><h4>Explorar</h4></a>
        </div>
        <div class="square_space">
            <img class="img_space" src="../static/img/mi_espacio.jpg" alt="foto de amigos reunidos">
            <a href="{{url_for('main.mi_espacio')}}" class="btn_space"><h4>Mi Espacio</h4></a>
        </div>
        <div class="square_connect">
            <img class="img_connect" src="../static/img/relacionate.jpg" alt="foto de personas conociendose">
            <a href="{{url_for('main.relacionate')}}" class="btn_connect"><h4>Relacionate</h4></a>
        </div>
    </div>

    <div class="footer">
                <div class="footer-links">
  
                  <a href="#">Terms of Use</a> | 
  
                  <a href="#">Privacy Policy</a> | 
  
                  <a href="#">Developers</a> | 
  
                  <a href="#">Contact</a> | 
  
                  <a href="#">About</a>
                  <h3>Copyright © Company - All rights reserved</h3>
                </div>   
                
                       
  

    </div>

    <!--<Script src="../static/js/feed.js"></Script>
    <Script>src="../static/js/susggestions.js"</Script>-->

    <script src="../static/js/buscador.js"> </script>

</body>
</html>

templates/mensajes.html
<!DOCTYPE html>
<html lang="sp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cairina Moschata</title>
</head>
<body>
    <h1>mensajes</h1>

</body>
</html>

templates/mi_espacio.html
<!DOCTYPE html>
<html lang="sp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cairina Moschata</title>
    <link rel="shortcut icon"  href="../static/img/favicon.png">
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/espacio.css" />
    <link rel="stylesheet" href="../static/fontawasome/css/all.min.css">
    
</head>
<body>
    <div id ="barra_estado"> 
        
        <div id="ctn-bars-search"> <!--search-input-->
            <a href="" target="_blank" hidden></a>
                <input type="text" id="inputSearch" placeholder="¿buscas a alguien? Escribe su nombre aquí" > <!--id="inputSearch"-->
                
                <div id="ctn-icon-search"> <!--<a href="{{url_for('main.resultados')}}">--><i class="fas fa-search" id="icon-search"></i></a> <!--id="icon-search"-->
                </div>
                <ul id ="box-search"> 
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> luisa</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> leo</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> shakira</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> marco</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> daniela</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> jbalvin</a></a></li>
                    
                </ul>
                <!--<div class="icon"><i class="fas fa-search"></i></div>-->
            </div>

       
        <!--<h2 class="icon_text">Cairina Moschata</h2> cambiar imagen a una con icono y letras-->
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/icon_cairina.jpg') }}" class="btn_icon" alt="icono de cairina"></a>
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/texto_logo_2.png') }}" class="txt_icon" alt="icono de cairina"></a>


        <a href="{{url_for('main.notificaciones')}}" id="btn_notification"><i class="fas fa-bell"></i></a>
        <a href="{{url_for('main.index')}}" id="btn_logout"><i class="fas fa-sign-out-alt"></i></a>
        <a href="{{url_for('main.mensajes')}}" id="btn_message"> <i class="fas fa-envelope"></i></a>
        <a href="{{url_for('main.perfil_user')}}" id="btn_user"><i class=" fas fa-user-circle"></i></i></a>
         <!-- En el div barra_estado se usan anchors en forma de botones para utilizar iconos de fontawesome
        es necesario tener las carpetas "svgs y webfonts" dentro del proyecto para que funcionen y utilizar un link como 
        se muestra en la linea 10 .....En la clase wrapper se encuenta todo lo relacionado a la barra de busqueda-->
      
    </div>

    <div class="nav_menu">
        <a href="{{url_for('main.feed')}}">Inicio</a> | 

        <a href="{{url_for('main.post')}}">Nuevo Post</a> |   

        <a href="{{url_for('main.explorar')}}">Explorar</a> | 

        <a href="{{url_for('main.relacionate')}}">Relacionate</a>

    </div>
    <h3 class="amigos">Tus amigos estan aquí</h3>

    <div class="resultado_busqueda"> <!--""-->
        <img src="../static/img/post _amigos.jpg" alt="foto de varias personas tomandose una selfie">
        <img src="../static/img/post _fut.jpg" alt="foto de hombre jugando futbol">
        <img src="../static/img/post _dann.jpg" alt="foto de mujer en la playa">
    </div>
    <div class="footer">
        <div class="footer-links">

          <a href="#">Terms of Use</a> | 

          <a href="#">Privacy Policy</a> | 

          <a href="#">Developers</a> | 

          <a href="#">Contact</a> | 

          <a href="#">About</a>
          <h3>Copyright © Company - All rights reserved</h3>
        </div>   
        
               
    </div>
    <script src="../static/js/buscador.js"> </script>
</body>



</html>

templates/relacionate.html
<!DOCTYPE html>
<html lang="sp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cairina Moschata</title>
    <link rel="shortcut icon"  href="../static/img/favicon.png">
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/relacionate.css" />
    <link rel="stylesheet" href="../static/fontawasome/css/all.min.css">
    
</head>
<body>
    <div id ="barra_estado"> 
        
        <div id="ctn-bars-search"> <!--search-input-->
            <a href="" target="_blank" hidden></a>
                <input type="text" id="inputSearch" placeholder="¿buscas a alguien? Escribe su nombre aquí" > <!--id="inputSearch"-->
                
                <div id="ctn-icon-search"> <!--<a href="{{url_for('main.resultados')}}">--><i class="fas fa-search" id="icon-search"></i></a> <!--id="icon-search"-->
                </div>
                <ul id ="box-search"> 
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> luisa</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> leo</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> shakira</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> marco</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> daniela</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> jbalvin</a></a></li>
                    
                </ul>
                <!--<div class="icon"><i class="fas fa-search"></i></div>-->
            </div>

       
        <!--<h2 class="icon_text">Cairina Moschata</h2> cambiar imagen a una con icono y letras-->
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/icon_cairina.jpg') }}" class="btn_icon" alt="icono de cairina"></a>
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/texto_logo_2.png') }}" class="txt_icon" alt="icono de cairina"></a>


        <a href="{{url_for('main.notificaciones')}}" id="btn_notification"><i class="fas fa-bell"></i></a>
        <a href="{{url_for('main.index')}}" id="btn_logout"><i class="fas fa-sign-out-alt"></i></a>
        <a href="{{url_for('main.mensajes')}}" id="btn_message"> <i class="fas fa-envelope"></i></a>
        <a href="{{url_for('main.perfil_user')}}" id="btn_user"><i class=" fas fa-user-circle"></i></i></a>
         <!-- En el div barra_estado se usan anchors en forma de botones para utilizar iconos de fontawesome
        es necesario tener las carpetas "svgs y webfonts" dentro del proyecto para que funcionen y utilizar un link como 
        se muestra en la linea 10 .....En la clase wrapper se encuenta todo lo relacionado a la barra de busqueda-->
      
    </div>

    <div class="nav_menu">
        <a href="feed.html">Inicio</a> | 

        <a href="nuevo_post.html">Nuevo Post</a> |   

        <a href="explorar.html">Tu espacio</a> | 

        <a href="mi_espacio.html">Mi espacio</a>

    </div>
    <h3 class="amigos">¿los conoces? ¡siguelos!</h3>

    <div class="resultado_busqueda"> <!--""-->
        <img src="../static/img/siguelos.jpg" alt="foto de varias personas tomandose una selfie">
    </div>
    <div class="footer">
        <div class="footer-links">

          <a href="#">Terms of Use</a> | 

          <a href="#">Privacy Policy</a> | 

          <a href="#">Developers</a> | 

          <a href="#">Contact</a> | 

          <a href="#">About</a>
          <h3>Copyright © Company - All rights reserved</h3>
        </div>   
        
               
    </div>
    <script src="../static/js/buscador.js"> </script>
</body>



</html>

templates/search_result.html
<!DOCTYPE html>
<html lang="sp">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cairina Moschata</title>
    <link rel="shortcut icon"  href="../static/img/favicon.png">
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/feed.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/search_result.css" />
    <link rel="stylesheet" href="../static/fontawasome/css/all.min.css">
    
</head>
<body>
    <div id ="barra_estado"> 
        
        <div id="ctn-bars-search"> <!--search-input-->
            <a href="" target="_blank" hidden></a>
                <input type="text" id="inputSearch" placeholder="¿buscas a alguien? Escribe su nombre aquí" > <!--id="inputSearch"-->
                
                <div id="ctn-icon-search"> <!--<a href="{{url_for('main.resultados')}}">--><i class="fas fa-search" id="icon-search"></i></a> <!--id="icon-search"-->
                </div>
                <ul id ="box-search"> 
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> luisa</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> leo</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> shakira</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> marco</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> daniela</a></a></li>
                    <li><a href="{{url_for('main.resultados')}}"><i class="fas fa-search"></i> jbalvin</a></a></li>
                    
                </ul>
                <!--<div class="icon"><i class="fas fa-search"></i></div>-->
            </div>
    
       
        <!--<h2 class="icon_text">Cairina Moschata</h2> cambiar imagen a una con icono y letras-->
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/icon_cairina.jpg') }}" class="btn_icon" alt="icono de cairina"></a>
        <a href="{{url_for('main.feed')}}" > <img src="{{ url_for('static', filename='/img/texto_logo_2.png') }}" class="txt_icon" alt="icono de cairina"></a>
    
    
        <a href="{{url_for('main.notificaciones')}}" id="btn_notification"><i class="fas fa-bell"></i></a>
        <a href="{{url_for('main.index')}}" id="btn_logout"><i class="fas fa-sign-out-alt"></i></a>
        <a href="{{url_for('main.mensajes')}}" id="btn_message"> <i class="fas fa-envelope"></i></a>
        <a href="{{url_for('main.perfil_user')}}" id="btn_user"><i class=" fas fa-user-circle"></i></i></a>
         <!-- En el div barra_estado se usan anchors en forma de botones para utilizar iconos de fontawesome
        es necesario tener las carpetas "svgs y webfonts" dentro del proyecto para que funcionen y utilizar un link como 
        se muestra en la linea 10 .....En la clase wrapper se encuenta todo lo relacionado a la barra de busqueda-->
      
    </div>

    <div class="nav_menu">
        <a href="{{url_for('main.feed')}}">Inicio</a> | 

        <a href="{{url_for('main.post')}}">Nuevo Post</a> |   

        <a href="{{url_for('main.explorar')}}">Explorar</a> | 

        <a href="{{url_for('main.mi_espacio')}}">Tu espacio</a> |

        <a href="{{url_for('main.relacionate')}}">Relacionate</a>



    </div>
    <h3 class="resultados">Resultados:</h3>

    <div class="resultado_busqueda"> <!--""-->
        <h5> No se encontraron resultados :(</h5>
        <p>
            Esto es una prueba para mostrar el funcionamiento del scroll bar!!!!.
            <br>
            <br>
            Aqui Va desplegada la lista de usuarios encontrados teniendo en cuenta los criterios de busqueda
            <br>
            <br>
            
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti consectetur minus deleniti culpa ducimus alias blanditiis, suscipit eligendi vel quam magni ad quasi iure? Nulla dolorum repellat atque laboriosam. Vel?
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti sequi provident expedita esse, nostrum corporis reiciendis, vel odio laboriosam dolorum distinctio totam, soluta delectus dolores vero. Eum libero laborum sunt. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti sequi provident expedita esse, nostrum corporis reiciendis, vel odio laboriosam dolorum distinctio totam, soluta delectus dolores vero. Eum libero laborum sunt.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti sequi provident expedita esse, nostrum corporis reiciendis, vel odio laboriosam dolorum distinctio totam, soluta delectus dolores vero. Eum libero laborum sunt. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti sequi provident expedita esse, nostrum corporis reiciendis, vel odio laboriosam dolorum distinctio totam, soluta delectus dolores vero. Eum libero laborum sunt.
        </p>
    </div>
    <div class="footer">
        <div class="footer-links">

          <a href="#">Terms of Use</a> | 

          <a href="#">Privacy Policy</a> | 

          <a href="#">Developers</a> | 

          <a href="#">Contact</a> | 

          <a href="#">About</a>
          <h3>Copyright © Company - All rights reserved</h3>
        </div>   
        
               
    </div>
    <script src="../static/js/buscador.js"> </script>
    
</body>



</html>